### ISSUE TITLE
Some queries are duplicated

### ISSUE THREAD

**Issue by Tropicalista** [yajra/laravel-admin-template#4]
Hi,

I've tried your template that is amazing. However some queries are duplicated, is this a bug?

**Comment by yajra** [comment]
Can you please specify the duplicated queries? I haven't updated this and some codes/errors maybe from the original fork, I made a lot of adjustments on this on my actual project but haven't applied the patch here.

**Comment by yajra** [comment]
I think this was due to a Laravel bug and is already fixed on the framework.
