### ISSUE TITLE
Cannot change input date format

### ISSUE THREAD

**Issue by ariefeko** [yajra/laravel-admin-template#5]
Hi,

I cannot save date input to my current local environment, i tried $tgl = date("Y-m-d", strtotime(Input::get('trm_tgltxt'))); but it fails, return the value to my database "01/01/1970"

Can you help me how to fix this?

**Comment by yajra** [comment]
Hi,

Are you using Eloquent or Query Builder? can you please paste your code here so I can check?

Thanks!

**Comment by ariefeko** [comment]
I'm using eloquent, here is my code:
Controller:

    public function postSimpan()
    {
        $title = Lang::get('admin/hstokins/title.hstokin_update');
        $hstokin = Hstokin::where('trm_no', '=', Input::get('trm_notxt'))->first();

        $rules = array(
            'trm_notxt'   => 'required|min:4',
            'kdgudangtxt' => 'required|min:3'
        );

        $validator = Validator::make(Input::all(), $rules);

        if ($validator->passes())
        {
            if (isset($hstokin)) { // edit
                
                // konversi input ke db
                $tgl = date("Y-m-d", strtotime(Input::get('trm_tgltxt')));
                $tempo = date("Y-m-d", strtotime(Input::get('trm_jt_tempotxt')));

                $hstokin->trm_no        = Input::get('trm_notxt');
                $hstokin->trm_tgl       = $tgl;
                $hstokin->trm_do        = Input::get('trm_dotxt');
                $hstokin->kdrek         = Input::get('kdrektxt');
                $hstokin->trm_tagihan   = Input::get('trm_tagihantxt');
                $hstokin->trm_jt_tempo  = $tempo;
                $hstokin->kdgudang      = Input::get('kdgudangtxt');

                $hstokin->save();
                //$tgl = null;
                //$tempo = null;

                //$tgl = date("d-m-Y", strtotime($hstokin->trm_tgl);
                //$tempo = date("d-m-Y", strtotime($hstokin->trm_jt_tempo);

                //$hstokin = Hstokin::where('trm_no', '=', Input::get('trm_notxt'))->first();
                //return View::make('admin.hstokins.index', compact('hstokin', 'tgl','tempo' , 'title'));
                return Redirect::back()->with('success', Lang::get('admin/hstokins/messages.update.success'));
            }
        }
        // Form validation failed
        return Redirect::to('admin/hstokins')->withInput()->withErrors($validator);
     }

views: modified form syntax

	{{ Form::open(array('action' => 'AdminHstokinsController@postSimpan','class' => 'form-horizontal')) }}
			<div class="form-group {{ $errors->has('trm_tgltxt') ? 'has-error' : '' }}">
				<label class="control-label col-sm-3" for="trm_tgltxt">Tanggal Terima:</label>
				<div class="col-sm-8">
					<div class="input-group">
						<div class="input-group-addon">
	                        <i class="fa fa-calendar"></i>
	                    </div>
					<input placeholder="dd/mm/yyyy" class="form-control" type="text" name="trm_tgltxt" id="trm_tgltxt" value="{{ Input::old('trm_tgltxt', isset($hstokin) ? $tgl : null) }}" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask/>
					{{ $errors->first('trm_tgltxt', '<span class="help-block">:message</span>') }}
					</div>
				</div>
			</div>
			<div class="form-group {{ $errors->has('trm_jt_tempotxt') ? 'has-error' : '' }}">
				<label class="control-label col-sm-3" for="trm_jt_tempotxt">Jatuh Tempo:</label>
				<div class="col-sm-8">
					<div class="input-group">
						<div class="input-group-addon">
	                        <i class="fa fa-calendar"></i>
	                    </div>
						<input placeholder="dd/mm/yyyy" class="form-control" type="text" name="trm_jt_tempotxt" id="trm_jt_tempotxt" value="{{ Input::old('trm_jt_tempotxt', isset($hstokin) ? $tempo : null) }}" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask />
						{{ $errors->first('trm_jt_tempotxt', '<span class="help-block">:message</span>') }}
					</div>
				</div>
			</div>
			...
			...
	{{ Form::close() }}


I also had re-set encryption key using "php artisan key:generate --env=local" and setting up my machine to local setting for date/time. still wont work for me

Btw, thanks for your nice adminlte theme, this help me alot :)

**Comment by yajra** [comment]
Hmm..  your code seems good but maybe try using `Carbon` when creating dates and use Eloquent date fields property just to make sure.

on your model `Hstokin` add code below: 
```php
protected $dates = ['trm_tgl', 'trm_jt_tempo'];
```
Note: Oracle is quite sensitive on dates.

[AdminLTE ](https://github.com/almasaeed2010/AdminLTE) is a work from another guy. ^_^

**Comment by ariefeko** [comment]
Thanks yajra, maybe I should try Carbon
