### ISSUE TITLE
Server side search datatable error 

### ISSUE THREAD

**Issue by andikamri** [yajra/laravel-admin-template#6]
Hello, 

I having an error when try to search in datatable when server side is on (is working like charm when server side is off), and here is the error message

SQLSTATE[42000]: Syntax error or access violation: 1582 Incorrect parameter count in the call to native function 'LOWER' (SQL: select count(*) as aggregate from (select '1' as row_count from `comments` left join `posts` on `posts`.`id` = `comments`.`post_id` left join `users` on `users`.`id` = `comments`.`user_id` where (LOWER() LIKE %lor% or LOWER() LIKE %lor% or LOWER() LIKE %lor% or LOWER() LIKE %lor% or LOWER() LIKE %lor%)) count_row_table)

any suggestion? thanks!

**Comment by yajra** [comment]
Hi, the error is on the datatables server side package. Did you update the packages? Maybe the latest release have some issues. But will check this later.

**Comment by yajra** [comment]
Btw: the package for datatables is https://github.com/yajra/laravel-datatables-oracle. Please update your composer and set the package version to `"yajra/laravel-datatables-oracle": "~3.0"`. You may have updated the packages and have download the Laravel 5 version.

**Comment by andikamri** [comment]
Thanks for the quick reply, i've already update the package to v3.3.12, but it stills produce an error

error: {type: "Illuminate\Database\QueryException",…}
file: "C:\xampp\htdocs\saptatours\vendor\laravel\framework\src\Illuminate\Database\Connection.php"
line: 625
message: "SQLSTATE[42000]: Syntax error or access violation: 1582 Incorrect parameter count in the call to native function 'LOWER' (SQL: select count(*) as aggregate from (select '1' as row_count from `users` where (LOWER() LIKE %ad% or LOWER() LIKE %ad% or LOWER() LIKE %ad% or LOWER() LIKE %ad%)) count_row_table)"
type: "Illuminate\Database\QueryException"

for addition, i'm using SQL and Laravel 4.2, thanks

**Comment by yajra** [comment]
Was able to replicate the issue. Kindly update the package again to [v3.3.13](https://github.com/yajra/laravel-datatables-oracle/tree/v3.3.13). Thanks!

**Comment by andikamri** [comment]
Now its working perfectly, thanks a lot!
